const bicStudents = [
  {
    firstName: "John",
    lastName: "Olalekan",
    email: "mohammedola1,234@gmail.com",
    matric: 204905,
    admin: 100100,
    admin: 100100,
  },
  {
    firstName: "John2",
    lastName: "Olalekan2",
    email: "mohammed2ola1234@gmail.com",
    matric: 213098,
    admin: 100100,
    admin: 100100,
  },
  {
    firstName: "John3",
    lastName: "Olalekan3",
    email: "mohammed3ola1234@gmail.com",
    matric: 213048,
    admin: 100100,
    admin: 100100,
  },
  {
    firstName: "John4",
    lastName: "Olalekan4",
    email: "mohammed4ola1234@gmail.com",
    matric: 215943,
    admin: 100100,
    admin: 100100,
  },
  {
    firstName: "John4",
    lastName: "Olalekan4",
    email: "mohammed4ola1234@gmail.com",
    matric: 206026,
    admin: 100100,
    admin: 100100,
  },
];

export default bicStudents;

export const BICSTUDENTS = [
  {
    firstName: "Ibraheem",
    lastName: "Bashir",
    email: "princehyebee@gmail.com",
    matric: 206011,
    admin: 100100,
  },
  {
    firstName: "Adedayo",
    lastName: "Tella",
    email: "adedayotella16@gmail.com",
    matric: 204918,
    admin: 100100,
  },
  {
    firstName: "Israel",
    lastName: "Abiola",
    email: "abiolaisrael86@gmail.com",
    matric: 205998,
    admin: 100100,
  },
  {
    firstName: "Oluwatosin",
    lastName: "Alonge",
    email: "oluwatosinalonge2001@gmail.com",
    matric: 206006,
    admin: 100100,
  },
  {
    firstName: "Qowiyah",
    lastName: "Zakariyau",
    email: "adedoyinzaka@gmail.com",
    matric: 206040,
    admin: 100100,
  },
  {
    firstName: "Oluwadarasimi",
    lastName: "Stephen",
    email: "daradamasus001@gmail.com",
    matric: 204916,
    admin: 100100,
  },
  {
    firstName: "kofoworola",
    lastName: "Akinwole",
    email: "Kofoworolaoyebisi@gmail.com",
    matric: 204897,
    admin: 100100,
  },
  {
    firstName: "Joseph",
    lastName: "Sule",
    email: "josephsule61@gmail.com",
    matric: 206038,
    admin: 100100,
  },
  {
    firstName: "Mercy",
    lastName: "Odewale",
    email: "olumercy014@gmail.com",
    matric: 206024,
    admin: 100100,
  },
  {
    firstName: "Sherifdeen",
    lastName: "Gazali",
    email: "sgazali900@stu.ui.edu.ng",
    matric: 204900,
    admin: 100100,
  },
  {
    firstName: "Precious",
    lastName: "Ogundipe",
    email: "preciousogundipe9688@gmail.com",
    matric: 204909,
    admin: 100100,
  },
  {
    firstName: "Adeayo",
    lastName: "Adewale",
    email: "adeayoadewale@gmail.com",
    matric: 204894,
    admin: 100100,
  },
  {
    firstName: "Barakat",
    lastName: "Azeez",
    email: "dianazeez247@gmail.com",
    matric: 206010,
    admin: 100100,
  },
  {
    firstName: "Boluwatife",
    lastName: "Oladoyin",
    email: "oladoyinboluwatife6@gmail.com",
    matric: 204910,
    admin: 100100,
  },
  {
    firstName: "Joseph-Peace",
    lastName: "Adekanye",
    email: "peacekanye@gmail.com",
    matric: 204890,
    admin: 100100,
  },
  {
    firstName: "Oluwafikayomi",
    lastName: "Iyayi",
    email: "Fikkyslim27@gmail.com",
    matric: 206019,
    admin: 100100,
  },
  {
    firstName: "David",
    lastName: "Ehusani",
    email: "ehusanidavid@gmail.com",
    matric: 204899,
    admin: 100100,
  },
  {
    firstName: "Rebecca",
    lastName: "Oyeleye",
    email: "royeleye036@stu.ui.edu.ng",
    matric: 206036,
    admin: 100100,
  },
  {
    firstName: "Tomilayo",
    lastName: "Akande",
    email: "akandetomilayoo@gmail.com",
    matric: 206003,
    admin: 100100,
  },
  {
    firstName: "Samuel",
    lastName: "Ajayi",
    email: "sammieajayi04@gmail.com",
    matric: 204896,
    admin: 100100,
  },
  {
    firstName: "Gbenga",
    lastName: "Olaseni",
    email: "gj.olaseni@gmail.com",
    matric: 206032,
    admin: 100100,
  },
  {
    firstName: "Wisdom",
    lastName: "Anyadike",
    email: "anyadikewisdom@gmail.com",
    matric: 206008,
    admin: 100100,
  },
  {
    firstName: "Vincent",
    lastName: "Unegbu",
    email: "unegbuvincent100@gmail.com",
    matric: 204920,
    admin: 100100,
  },
  {
    firstName: "Opeyemi",
    lastName: "Latinwo",
    email: "olatinwo068@stu.ui.edu.ng",
    matric: 213068,
    admin: 100100,
  },
  {
    firstName: "Timilehin",
    lastName: "Ogunlumade",
    email: "ogunlumadet@gmail.com",
    matric: 206026,
    admin: 100100,
  },
  {
    firstName: "Temitope",
    lastName: "Kolawole",
    email: "temmiewade@gmail.com",
    matric: 206020,
    admin: 100100,
  },
  {
    firstName: "Basit",
    lastName: "Alayande",
    email: "alayandebasit@gmail.com",
    matric: 206005,
    admin: 100100,
  },
  {
    firstName: "Frederick",
    lastName: "Udobioroh",
    email: "fredericcudobioroh@gmail.com",
    matric: 206039,
    admin: 100100,
  },
  {
    firstName: "OkikiJesu",
    lastName: "Oladokun",
    email: "oladokunokikijesu@gmail.com",
    matric: 206030,
    admin: 100100,
  },
  {
    firstName: "Joseph",
    lastName: "Ariole",
    email: "Josephariole7@gmail.com",
    matric: 190762,
    admin: 100100,
  },
  {
    firstName: "Azeez",
    lastName: "Olatunji",
    email: "olatunjiazeez62@gmail.com",
    matric: 206033,
    admin: 100100,
  },
  {
    firstName: "Oluwatosin",
    lastName: "Owolabi",
    email: "Olutosin005@gmail.com",
    matric: 204914,
    admin: 100100,
  },
  {
    firstName: "Deborah",
    lastName: "Ajogbor",
    email: "ajogbordeborah@gmail.com",
    matric: 206002,
    admin: 100100,
  },
  {
    firstName: "Christian",
    lastName: "Nte",
    email: "christiante120@gmail.com",
    matric: 206021,
    admin: 100100,
  },
  {
    firstName: "Aisha",
    lastName: "Hameed",
    email: "Hameedaishabolaji@gmail.com",
    matric: 204901,
    admin: 100100,
  },
  {
    firstName: "Blessing",
    lastName: "Adekunle",
    email: "blessingirl0709@gmail.com",
    matric: 204891,
    admin: 100100,
  },
  {
    firstName: "Rejoice",
    lastName: "Oladejo",
    email: "rejoiceay85@gmail.com",
    matric: 206028,
    admin: 100100,
  },
  {
    firstName: "Seun",
    lastName: "Sulaimon",
    email: "seundremy@gmail.com",
    matric: 198342,
    admin: 100100,
  },
  {
    firstName: "Gideon",
    lastName: "Mbakwe",
    email: "gidm37@gmail.com",
    matric: 204904,
    admin: 100100,
  },
  {
    firstName: "Chidera",
    lastName: "Chiedu",
    email: "chieduchidera@gmail.com",
    matric: 204898,
    admin: 100100,
  },
  {
    firstName: "Mary",
    lastName: "Adeyemo",
    email: "adejokemary99@gmail.com",
    matric: 204895,
    admin: 100100,
  },
  {
    firstName: "Jude",
    lastName: "Olanrewaju",
    email: "jeylanre@gmail.com",
    matric: 204913,
    admin: 100100,
  },
  {
    firstName: "Ogo-oluwa",
    lastName: "Ekanola",
    email: "Ogoekan20@gmail.com",
    matric: 206013,
    admin: 100100,
  },
  {
    firstName: "Chinedu",
    lastName: "Kenechukwu",
    email: "Kenechukwu.Susan@gmail.com",
    matric: 204903,
    admin: 100100,
  },
  {
    firstName: "Moses",
    lastName: "Ayaosi",
    email: "oscarmoses93@gmail.com",
    matric: 206009,
    admin: 100100,
  },
  {
    firstName: "Victor",
    lastName: "Onyebuchi",
    email: "vonyebuchi094@stu.ui.edu.ng",
    matric: 213094,
    admin: 100100,
  },
  {
    firstName: "Jeremiah",
    lastName: "Abdul",
    email: "jabdul576@stu.ui.edu.ng",
    matric: 220576,
    admin: 100100,
  },
  {
    firstName: "Fadlullah",
    lastName: "Abdul-Azeez",
    email: "fabdulazeez577@stu.ui.edu.ng",
    matric: 220577,
    admin: 100100,
  },
  {
    firstName: "Alli",
    lastName: "Abdulraheem",
    email: "aabdulraheem578@stu.ui.edu.ng",
    matric: 220578,
    admin: 100100,
  },
  {
    firstName: "Ayoola",
    lastName: "Abidoye",
    email: "aabidoye580@stu.ui.edu.ng",
    matric: 220580,
    admin: 100100,
  },
  {
    firstName: "Israel",
    lastName: "Abisoye",
    email: "Iabisoye581@stu.ui.edu.ng",
    matric: 220581,
    admin: 100100,
  },
  {
    firstName: "Ilerioluwa",
    lastName: "Adebayo",
    email: "Iadebayo582@stu.ui.edu.ng",
    matric: 220582,
    admin: 100100,
  },
  {
    firstName: "Oyindamola",
    lastName: "Adebola",
    email: "Oadebola582@stu.ui.edu.ng",
    matric: 220583,
    admin: 100100,
  },
  {
    firstName: "Marvellous",
    lastName: "Adefemi",
    email: "madefemi584@stu.ui.edu.ng",
    matric: 220584,
    admin: 100100,
  },
  {
    firstName: "Adetomiwa",
    lastName: "Ademola",
    email: "aademola587@stu.ui.edu.ng",
    matric: 220587,
    admin: 100100,
  },
  {
    firstName: "Victoria",
    lastName: "Adeoye",
    email: "vadeoye590@stu.ui.edu.ng",
    matric: 220590,
    admin: 100100,
  },
  {
    firstName: "Kabeerah",
    lastName: "Aderibigbe",
    email: "kaderibigbe591@stu.ui.edu.ng",
    matric: 220591,
    admin: 100100,
  },
  {
    firstName: "Priscilla",
    lastName: "Adeseun",
    email: "padeseun592@stu.ui.edu.ng",
    matric: 220592,
    admin: 100100,
  },
  {
    firstName: "Opeyemi",
    lastName: "Adesokan",
    email: "oadesokan593@stu.ui.edu.ng",
    matric: 220593,
    admin: 100100,
  },
  {
    firstName: "Ezekiel",
    lastName: "Afolabi",
    email: "eafolabi595@stu.ui.edu.ng",
    matric: 220595,
    admin: 100100,
  },
  {
    firstName: "Oluwaseyi",
    lastName: "Ajiboye",
    email: "oajiboye599@stu.ui.edu.ng",
    matric: 220599,
    admin: 100100,
  },
  {
    firstName: "Elizabeth",
    lastName: "Akinniretemitope",
    email: "Takinnire600@stu.ui.edu.ng",
    matric: 220600,
    admin: 100100,
  },
  {
    firstName: "Cynthia",
    lastName: "Akpala",
    email: "cakpala601@stu.ui.edu.ng",
    matric: 220601,
    admin: 100100,
  },
  {
    firstName: "Usman",
    lastName: "Alabi",
    email: "ualabi602@stu.ui.edu.ng",
    matric: 220602,
    admin: 100100,
  },
  {
    firstName: "Temiloluwa",
    lastName: "Aloba",
    email: "taloba604@stu.ui.edu.ng",
    matric: 220604,
    admin: 100100,
  },
  {
    firstName: "Ibrahim",
    lastName: "Arabiyi",
    email: "iarabiyi605@stu.ui.edu.ng",
    matric: 220605,
    admin: 100100,
  },
  {
    firstName: "Folakemi",
    lastName: "Ayeni",
    email: "fayeni608@stu.ui.edu.ng",
    matric: 220608,
    admin: 100100,
  },
  {
    firstName: "Victor",
    lastName: "Benedict",
    email: "vBenedict610@stu.ui.edu.ng",
    matric: 220610,
    admin: 100100,
  },
  {
    firstName: "Christopher",
    lastName: "Eyebiokin",
    email: "ceyebiokin611@stu.ui.edu.ng",
    matric: 220611,
    admin: 100100,
  },
  {
    firstName: "Damilare",
    lastName: "Fadare",
    email: "dfadare612@stu.ui.edu.ng",
    matric: 220612,
    admin: 100100,
  },
  {
    firstName: "Israel",
    lastName: "Famuyiwa",
    email: "ifamuyiwa613@stu.ui.edu.ng",
    matric: 220613,
    admin: 100100,
  },
  {
    firstName: "Anuoluwapo",
    lastName: "Hassan",
    email: "ahassan615@stu.ui.edu.ng",
    matric: 220615,
    admin: 100100,
  },
  {
    firstName: "Andrew",
    lastName: "Idakwo",
    email: "aidakwo616@stu.ui.edu.ng",
    matric: 220616,
    admin: 100100,
  },
  {
    firstName: "Daniel",
    lastName: "Isaac-orji",
    email: "disaacorji618@stu.ui.edu.ng",
    matric: 220618,
    admin: 100100,
  },
  {
    firstName: "Peter",
    lastName: "Jibril",
    email: "pjibril619@stu.ui.edu.ng",
    matric: 220619,
    admin: 100100,
  },
  {
    firstName: "Chukwuemeka",
    lastName: "Madu",
    email: "cmadu620@stu.ui.edu.ng",
    matric: 220620,
    admin: 100100,
  },
  {
    firstName: "Abdulhaleem",
    lastName: "Mogaji",
    email: "amogaji622@stu.ui.edu.ng",
    matric: 220622,
    admin: 100100,
  },
  {
    firstName: "Favour",
    lastName: "Momodu",
    email: "fmomodu623@stu.ui.edu.ng",
    matric: 220623,
    admin: 100100,
  },
  {
    firstName: "Moses",
    lastName: "Odesola",
    email: "modesola624@stu.ui.edu.ng",
    matric: 220624,
    admin: 100100,
  },
  {
    firstName: "Chisom",
    lastName: "OgeneJoan",
    email: "jogene625@stu.ui.edu.ng",
    matric: 220625,
    admin: 100100,
  },
  {
    firstName: "Ayobami",
    lastName: "Ogundeji",
    email: "aogundeji626@stu.ui.edu.ng",
    matric: 220626,
    admin: 100100,
  },
  {
    firstName: "Wasiu",
    lastName: "Ogundimu",
    email: "wogundimu627@stu.ui.edu.ng",
    matric: 220627,
    admin: 100100,
  },
  {
    firstName: "Emmanuel",
    lastName: "Ogunniran",
    email: "eogunniran628@stu.ui.edu.ng",
    matric: 220628,
    admin: 100100,
  },
  {
    firstName: "Celina",
    lastName: "Ogunsola",
    email: "cogunsola629@stu.ui.edu.ng",
    matric: 220629,
    admin: 100100,
  },
  {
    firstName: "Ekundayo",
    lastName: "Okemuyiwa",
    email: "eokemuyiwa630@stu.ui.edu.ng",
    matric: 220630,
    admin: 100100,
  },
  {
    firstName: "Inemesit",
    lastName: "Okon",
    email: "iokon631@stu.ui.edu.ng",
    matric: 220631,
    admin: 100100,
  },
  {
    firstName: "Sukurat",
    lastName: "Okunola",
    email: "sokunola632@stu.ui.edu.ng",
    matric: 220632,
    admin: 100100,
  },
  {
    firstName: "Oyindamola",
    lastName: "Oladokun",
    email: "ooladokun634@stu.ui.edu.ng",
    matric: 220634,
    admin: 100100,
  },
  {
    firstName: "Esther",
    lastName: "Oladunjoye",
    email: "eoladunjoye635@stu.ui.edu.ng",
    matric: 220635,
    admin: 100100,
  },
  {
    firstName: "Adebola",
    lastName: "Olagbemi",
    email: "aolagbemi636@stu.ui.edu.ng",
    matric: 220636,
    admin: 100100,
  },
  {
    firstName: "Oluwatodimu",
    lastName: "Olumodeji",
    email: "oolumodeji640@stu.ui.edu.ng",
    matric: 220640,
    admin: 100100,
  },
  {
    firstName: "Julius",
    lastName: "Peter",
    email: "jpeter645@stu.ui.edu.ng",
    matric: 220645,
    admin: 100100,
  },
  {
    firstName: "Waris",
    lastName: "Salawudeen",
    email: "wsalawudeen647@stu.ui.edu.ng",
    matric: 220647,
    admin: 100100,
  },
  {
    firstName: "Wahab",
    lastName: "Taofeek",
    email: "wtaofeek649@stu.ui.edu.ng",
    matric: 220649,
    admin: 100100,
  },
  {
    firstName: "Usman",
    lastName: "Tella",
    email: "utella650@stu.ui.edu.ng",
    matric: 220650,
    admin: 100100,
  },
  {
    firstName: "Mariam",
    lastName: "Yakub",
    email: "myakub651@stu.ui.edu.ng",
    matric: 220651,
    admin: 100100,
  },
  {
    firstName: "Abdulrasheed",
    lastName: "Ojediran",
    email: "aojediran728@stu.ui.edu.ng",
    matric: 223728,
    admin: 100100,
  },
  {
    firstName: "Adedamola",
    lastName: "Ajibade",
    email: "aajibade821@stu.ui.edu.ng",
    matric: 224821,
    admin: 100100,
  },
  {
    firstName: "Samuel",
    lastName: "Olukotun",
    email: "solukotun848@stu.ui.edu.ng",
    matric: 224848,
    admin: 100100,
  },
  {
    firstName: "Abayomi",
    lastName: "Olusanya",
    email: "aolusanya875@stu.ui.edu.ng",
    matric: 224875,
    admin: 100100,
  },
  {
    firstName: "Olamide",
    lastName: "Adekoya",
    email: "oadekoya879@stu.ui.edu.ng",
    matric: 224879,
    admin: 100100,
  },
  {
    firstName: "Isreal",
    lastName: "Olabiran",
    email: "iolabiran884@stu.ui.edu.ng",
    matric: 224884,
    admin: 100100,
  },
  {
    firstName: "Femi",
    lastName: "Olaosebikan",
    email: "foluosebikan906@stu.ui.edu.ng",
    matric: 224906,
    admin: 100100,
  },
  {
    firstName: "Israel",
    lastName: "Oladepo",
    email: "ioladepo911@stu.ui.edu.ng",
    matric: 224911,
    admin: 100100,
  },
  {
    firstName: "Opeyemi",
    lastName: "Oyedokun",
    email: "ooyedokun912@stu.ui.edu.ng",
    matric: 224912,
    admin: 100100,
  },
  {
    firstName: "Abdulhakeem",
    lastName: "Olanrewaju",
    email: "aolanrewaju916@stu.ui.edu.ng",
    matric: 224916,
    admin: 100100,
  },
  {
    firstName: "Olumide",
    lastName: "Saka",
    email: "osaka920@stu.ui.edu.ng",
    matric: 224920,
    admin: 100100,
  },
  {
    firstName: "Israel",
    lastName: "Akinyemi",
    email: "iakinyemi943@stu.ui.edu.ng",
    matric: 224943,
    admin: 100100,
  },
  {
    firstName: "AbdulAzeez",
    lastName: "Aina",
    email: "aaina951@stu.ui.edu.ng",
    matric: 224951,
    admin: 100100,
  },
  {
    firstName: "Gbenga",
    lastName: "Salawu",
    email: "gsalawu968@stu.ui.edu.ng",
    matric: 224968,
    admin: 100100,
  },
  {
    firstName: "Oluwatomisin",
    lastName: "Adeyemo",
    email: "oadeyemo972@stu.ui.edu.ng",
    matric: 224972,
    admin: 100100,
  },
  {
    firstName: "Maryam",
    lastName: "Akinkunle",
    email: "makinkunle975@stu.ui.edu.ng",
    matric: 224975,
    admin: 100100,
  },
  {
    firstName: "Racheal",
    lastName: "Abiola",
    email: "rabiola991@stu.ui.edu.ng",
    matric: 224991,
    admin: 100100,
  },
  {
    firstName: "Israel",
    lastName: "Oluwole",
    email: "ioluwole996@stu.ui.edu.ng",
    matric: 224996,
    admin: 100100,
  },
  {
    firstName: "Samuel",
    lastName: "ABHAREYI",
    email: "abhareyiehigiade@gmail.com",
    matric: 213035,
    admin: 100100,
  },
  {
    firstName: "Damilola",
    lastName: "ADEBOWALE",
    email: "Dadebowale038@stu.ui.edu.ng",
    matric: 213038,
    admin: 100100,
  },
  {
    firstName: "Ikeoluwa",
    lastName: "ADEDOYIN",
    email: "ikeoluwaadedoyin02@gmail.com",
    matric: 213039,
    admin: 100100,
  },
  {
    firstName: "Taofeek",
    lastName: "ADEYEMI",
    email: "tadeyemi042@stu.ui.edu.ng",
    matric: 213042,
    admin: 100100,
  },
  {
    firstName: "Oluwafunmilola",
    lastName: "AJAYI",
    email: "oajayi044@stu.ui.edu.ng",
    matric: 213044,
    admin: 100100,
  },
  {
    firstName: "Darasimi",
    lastName: "OLURANTI",
    email: "olurantioluwadara@gmail.com",
    matric: 214547,
    admin: 100100,
  },
  {
    firstName: "Kolade",
    lastName: "AKINTUNDE",
    email: "kakintunde047@stu.ui.edu.ng",
    matric: 213047,
    admin: 100100,
  },
  {
    firstName: "Elias",
    lastName: "ALEEM",
    email: "aleemelias@gmail.com",
    matric: 213048,
    admin: 100100,
  },
  {
    firstName: "Chimebuka",
    lastName: "ANYANWU",
    email: "chimebukaanyanwu@gmail.com",
    matric: 213049,
    admin: 100100,
  },
  {
    firstName: "Samuel",
    lastName: "ARO",
    email: "saro050@stu.ui.edu.ng",
    matric: 213050,
    admin: 100100,
  },
  {
    firstName: "Godwin",
    lastName: "ASUQUO",
    email: "gmarioz138@gmail.com",
    matric: 213051,
    admin: 100100,
  },
  {
    firstName: "Tosin",
    lastName: "BABAJIDE",
    email: "btosin747@gmail.com",
    matric: 213055,
    admin: 100100,
  },
  {
    firstName: "Idris",
    lastName: "BELLO",
    email: "ibello056@stu.ui.edu.ng",
    matric: 213056,
    admin: 100100,
  },
  {
    firstName: "Deborah",
    lastName: "EJEBU",
    email: "dejebu059@stu.ui.edu.ng",
    matric: 213059,
    admin: 100100,
  },
  {
    firstName: "Ifeanyichukwu",
    lastName: "EZE",
    email: "ifeanyichukwu91@gmail.com",
    matric: 213060,
    admin: 100100,
  },
  {
    firstName: "Christian",
    lastName: "FASIKU",
    email: "fasikuchristian@gmail.com",
    matric: 213063,
    admin: 100100,
  },
  {
    firstName: "Olajumoke",
    lastName: "FATAI",
    email: "ofatai574@stu.ui.edu.ng",
    matric: 213574,
    admin: 100100,
  },
  {
    firstName: "Ridwan",
    lastName: "HASSAN",
    email: "rhassan064@stu.ui.edu.ng",
    matric: 213064,
    admin: 100100,
  },
  {
    firstName: "Enedudu",
    lastName: "IDOKO",
    email: "idokoenedudu@gmail.com",
    matric: 204902,
    admin: 100100,
  },
  {
    firstName: "Favour",
    lastName: "JOEL",
    email: "fjoel065@stu.ui.edu.ng",
    matric: 213065,
    admin: 100100,
  },
  {
    firstName: "Oreoluwa",
    lastName: "KAYODE",
    email: "okayode066@stu.ui.edu.ng",
    matric: 213066,
    admin: 100100,
  },
  {
    firstName: "Ahmed",
    lastName: "LASISI",
    email: "alasisi067@stu.ui.edu.ng",
    matric: 213067,
    admin: 100100,
  },
  {
    firstName: "ARABA",
    lastName: "LAWRENCE",
    email: "alawrence069@stu.ui.edu.ng",
    matric: 213069,
    admin: 100100,
  },
  {
    firstName: "Adeola",
    lastName: "LIADI",
    email: "adeolaliadi8@gmail.com",
    matric: 213070,
    admin: 100100,
  },
  {
    firstName: "Nnamdi",
    lastName: "MARK",
    email: "marknnamdi80@gmail.com",
    matric: 213071,
    admin: 100100,
  },
  {
    firstName: "Ahmed",
    lastName: "MURAINA",
    email: "amuraina072@stu.ui.edu.ng",
    matric: 213072,
    admin: 100100,
  },
  {
    firstName: "Jesse",
    lastName: "NWAOKOLO",
    email: "jnwaokolo073@stu.ui.edu.ng",
    matric: 213073,
    admin: 100100,
  },
  {
    firstName: "Faith Iberi",
    lastName: "OCHUBE",
    email: "fochube074@stu.ui.edu.ng",
    matric: 213074,
    admin: 100100,
  },
  {
    firstName: "Stephen",
    lastName: "ODELEYE",
    email: "sodeleye075@stu.ui.edu.ng",
    matric: 213075,
    admin: 100100,
  },
  {
    firstName: "Emmanuel",
    lastName: "OGUNDIPE",
    email: "eogundipe077@stu.ui.edu.ng",
    matric: 213077,
    admin: 100100,
  },
  {
    firstName: "Olanrewaju",
    lastName: "OJEKUNLE",
    email: "oojekunle080@stu.ui.edu.ng",
    matric: 213080,
    admin: 100100,
  },
  {
    firstName: "Sherifat",
    lastName: "OJEKUNLE",
    email: "olamiojekunle@gmail.com",
    matric: 213081,
    admin: 100100,
  },
  {
    firstName: "Daniel",
    lastName: "OJENIRAN",
    email: "dojeniran082@stu.ui.edu.ng",
    matric: 213082,
    admin: 100100,
  },
  {
    firstName: "Joy",
    lastName: "OJI",
    email: "ojijoyadaeze@gmail.com",
    matric: 213083,
    admin: 100100,
  },
  {
    firstName: "Anthony",
    lastName: "OKEIBUNO",
    email: "aokeibuno084@stu.ui.edu.ng",
    matric: 213084,
    admin: 100100,
  },
  {
    firstName: "Babatunde",
    lastName: "OLABUNTU",
    email: "olabuntufizzy@gmail.com",
    matric: 213087,
    admin: 100100,
  },
  {
    firstName: "Fadilat",
    lastName: "OLALERU",
    email: "folaleru088@stu.ui.edu.ng",
    matric: 213088,
    admin: 100100,
  },
  {
    firstName: "Adedamola",
    lastName: "OLAOYE",
    email: "adedamolaolaoye027@gmail.com",
    matric: 213090,
    admin: 100100,
  },
  {
    firstName: "Oladayo",
    lastName: "OLATUNJI",
    email: "oolatunji092@stu.ui.edu.ng",
    matric: 213092,
    admin: 100100,
  },
  {
    firstName: "Bolade",
    lastName: "OLUSOGBON",
    email: "bolusogbon093@stu.ui.edu.ng",
    matric: 213093,
    admin: 100100,
  },
  {
    firstName: "Vine",
    lastName: "ONYEMUWA",
    email: "vonyemuwa095@stu.ui.edu.ng",
    matric: 213095,
    admin: 100100,
  },
  {
    firstName: "Ayoola",
    lastName: "OWOLABI",
    email: "aowolabi097@stu.ui.edu.ng",
    matric: 213097,
    admin: 100100,
  },
  {
    firstName: "Israel",
    lastName: "OYEBAMIJI",
    email: "ooyebamiji35@gmail.com",
    matric: 213098,
    admin: 100100,
  },
  {
    firstName: "Feranmi",
    lastName: "OYEDIRAN",
    email: "foyediran099@stu.ui.edu.ng",
    matric: 213099,
    admin: 100100,
  },
  {
    firstName: "Samuel",
    lastName: "OYEYINKA",
    email: "soyeyinka101@stu.ui.edu.ng",
    matric: 213101,
    admin: 100100,
  },
  {
    firstName: "Shakirat",
    lastName: "RAJI",
    email: "rajishakirat2030@gmail.com",
    matric: 213104,
    admin: 100100,
  },
  {
    firstName: "Marvellous",
    lastName: "SALAMI",
    email: "salamimarvellous2017@gmail.com",
    matric: 213105,
    admin: 100100,
  },
  {
    firstName: "Omokolade",
    lastName: "SHENKALE",
    email: "oshenkale106@stu.ui.edu.ng",
    matric: 213106,
    admin: 100100,
  },
  {
    firstName: "Samuel",
    lastName: "UMAH",
    email: "sumah107@stu.ui.edu.ng",
    matric: 213107,
    admin: 100100,
  },
  {
    firstName: "Favour",
    lastName: "ADEYEMI",
    email: "ayooluwafavour1@gmail.com",
    matric: 197747,
    admin: 100100,
  },
  {
    firstName: "Iyanuoluwa",
    lastName: "AINA",
    email: "iyanuoluwaaina09@gmail.com",
    matric: 214485,
    admin: 100100,
  },
  {
    firstName: "Jude",
    lastName: "AWOLAJA",
    email: "Judeawolaja@gmail.com",
    matric: 220607,
    admin: 100100,
  },
  {
    firstName: "Abiodun",
    lastName: "AYINLA",
    email: "zyncetayinla@gmail.com",
    matric: 214499,
    admin: 100100,
  },
  {
    firstName: "Abdulrasak",
    lastName: "Sholanke",
    email: "sholankeabdulrasak@gmail.com",
    matric: 229160,
    admin: 100100,
  },
  {
    firstName: "Christopher",
    lastName: "Onuh",
    email: "manofscience8@gmail.com",
    matric: 229114,
    admin: 100100,
  },
  {
    firstName: "Affoo-nsisong",
    lastName: "Okon",
    email: "affoonsisongokon@gmail.com",
    matric: 229142,
    admin: 100100,
  },
  {
    firstName: "Alimot",
    lastName: "Ahmod",
    email: "haleemahahmod@gmail.com",
    matric: 229097,
    admin: 100100,
  },
  {
    firstName: "Qudus",
    lastName: "Ibrahim",
    email: "qdsibrahim03@gmail.com",
    matric: 229124,
    admin: 100100,
  },
  {
    firstName: "Hassan",
    lastName: "Ayantunde",
    email: "Hassanayantunde@gmail.com",
    matric: 229107,
    admin: 100100,
  },
  {
    firstName: "Emmanuel",
    lastName: "Edun",
    email: "edunemmanuel16@gmail.com",
    matric: 229116,
    admin: 100100,
  },
  {
    firstName: "Halleluyah",
    lastName: "Akinsanya",
    email: "abiodunhalleluyah@gmail.com",
    matric: 229101,
    admin: 100100,
  },
  {
    firstName: "Igbagboyemi",
    lastName: "Opadele",
    email: "paulightdivine@gmail.com",
    matric: 232158,
    admin: 100100,
  },
  {
    firstName: "Abidemi",
    lastName: "Okoya",
    email: "okoyaolamide20@gmail.com",
    matric: 229143,
    admin: 100100,
  },
  {
    firstName: "Gerald",
    lastName: "Okoh",
    email: "geraldokoh2004@gmail.com",
    matric: 229141,
    admin: 100100,
  },
  {
    firstName: "Ayomide",
    lastName: "Isenodi",
    email: "isenodiayomide20@gmail.com",
    matric: 229128,
    admin: 100100,
  },
  {
    firstName: "David",
    lastName: "Egbuna",
    email: "egbunadavid232@gmail.com",
    matric: 229118,
    admin: 100100,
  },
  {
    firstName: "Oluwakomiyo",
    lastName: "Olu-Jordan",
    email: "komiyojordan@gmail.com",
    matric: 220023,
    admin: 100100,
  },
  {
    firstName: "Timilehin",
    lastName: "Aminu",
    email: "taminu103@stu.ui.edu.ng",
    matric: 229103,
    admin: 100100,
  },
  {
    firstName: "Emmanuel",
    lastName: "Adebayo",
    email: "herdeboy7@gmail.com",
    matric: 229089,
    admin: 100100,
  },
  {
    firstName: "Ayobami",
    lastName: "Oyelola",
    email: "oyelolaayobami098@gmail.com",
    matric: 229156,
    admin: 100100,
  },
  {
    firstName: "Goodness",
    lastName: "Oluwasina",
    email: "goodnessoluwasina@gmail.com",
    matric: 229151,
    admin: 100100,
  },
  {
    firstName: "Anuoluwa",
    lastName: "Ogunsola",
    email: "ogunsolaanuoluwa1@gmail.com",
    matric: 229138,
    admin: 100100,
  },
  {
    firstName: "Paul",
    lastName: "Okpara",
    email: "paulifeanyi99@gmail.com",
    matric: 229144,
    admin: 100100,
  },
  {
    firstName: "Jeremiah",
    lastName: "Olugbogi",
    email: "jeremiaholugbogi@gmail.com",
    matric: 229148,
    admin: 100100,
  },
  {
    firstName: "Toluwani",
    lastName: "Obatoke",
    email: "obatoketoluwani@gmail.com",
    matric: 229134,
    admin: 100100,
  },
  {
    firstName: "Happiness",
    lastName: "Ojo",
    email: "olamidehappiness29@gmail.com",
    matric: 229140,
    admin: 100100,
  },
  {
    firstName: "Mercy",
    lastName: "Oluwafemi",
    email: "mercy252005@gmail.com",
    matric: 229149,
    admin: 100100,
  },
  {
    firstName: "Joshua",
    lastName: "Ayobami",
    email: "ayobamijoshua055@gmail.com",
    matric: 229108,
    admin: 100100,
  },
  {
    firstName: "Habeeb",
    lastName: "Sirojudeen",
    email: "sirhabopeyemi56@gmail.com",
    matric: 229161,
    admin: 100100,
  },
  {
    firstName: "Boluwatife",
    lastName: "Osunnuga",
    email: "osunnugaboluwatife@gmail.com",
    matric: 229154,
    admin: 100100,
  },
  {
    firstName: "Mayowa",
    lastName: "Egbewusi",
    email: "egbewusimayowa@gmail.com",
    matric: 229117,
    admin: 100100,
  },
  {
    firstName: "Abdullahi",
    lastName: "Sulaimon",
    email: "asulaimon162@stu.ui.edu.ng",
    matric: 229162,
    admin: 100100,
  },
  {
    firstName: "Jonah",
    lastName: "Epitike",
    email: "jonahokwe@gmail.com",
    matric: 229120,
    admin: 100100,
  },
  {
    firstName: "Donaldson",
    lastName: "Olayanju",
    email: "olayanjudonaldson@gmail.com",
    matric: 229147,
    admin: 100100,
  },
  {
    firstName: "Kehinde",
    lastName: "Omotoso",
    email: "omotosokehinde2002@gmail.com",
    matric: 229153,
    admin: 100100,
  },
  {
    firstName: "Victor",
    lastName: "Loto",
    email: "valtonvic@gmail.com",
    matric: 229132,
    admin: 100100,
  },
  {
    firstName: "Tiwalade",
    lastName: "Ogunseye",
    email: "tiwaladeisaac70@gmail.com",
    matric: 229137,
    admin: 100100,
  },
  {
    firstName: "Damilola",
    lastName: "Akinrinade",
    email: "akinkeji2@gmail.com",
    matric: 229100,
    admin: 100100,
  },
  {
    firstName: "Glory",
    lastName: "Daniel",
    email: "gloryedaniel752@gmail.com",
    matric: 229115,
    admin: 100100,
  },
  {
    firstName: "Deborah",
    lastName: "Abiona",
    email: "Abionadeborah2000@gmail.com",
    matric: 229088,
    admin: 100100,
  },
  {
    firstName: "Daniel",
    lastName: "Oyibo",
    email: "Danick1018@gmail.com",
    matric: 229158,
    admin: 100100,
  },
  {
    firstName: "Zainab",
    lastName: "Alabi",
    email: "zainabkanyinsolaalabi@gmail.com",
    matric: 229102,
    admin: 100100,
  },
  {
    firstName: "Abubakar",
    lastName: "Idris",
    email: "idrisabu830@gmail.com",
    matric: 229126,
    admin: 100100,
  },
  {
    firstName: "Trust",
    lastName: "Kingsley",
    email: "kingsleytrust0@gmail.com",
    matric: 229129,
    admin: 100100,
  },
  {
    firstName: "Kehinde",
    lastName: "Olatunji",
    email: "rachealkehinde2001@gmail.com",
    matric: 229146,
    admin: 100100,
  },
  {
    firstName: "Goodness",
    lastName: "Igwe",
    email: "goodnessigwe2003@gmail.com",
    matric: 229127,
    admin: 100100,
  },
  {
    firstName: "Boluwatife",
    lastName: "Gidado",
    email: "gidadoboluwatife@gmail.com",
    matric: 229122,
    admin: 100100,
  },
  {
    firstName: "Saheed",
    lastName: "Musa",
    email: "Musa16saheed@gmail.com",
    matric: 229133,
    admin: 100100,
  },
  {
    firstName: "Philip",
    lastName: "Idowu",
    email: "idowuphilip84@gmail.com",
    matric: 229125,
    admin: 100100,
  },
  {
    firstName: "Zainab",
    lastName: "Bamgbola",
    email: "zainabbamgbola97@gmail.con",
    matric: 229111,
    admin: 100100,
  },
  {
    firstName: "Victoria",
    lastName: "Adetoro",
    email: "adetorovictoria632@gmail.com",
    matric: 229095,
    admin: 100100,
  },
  {
    firstName: "Salem",
    lastName: "Ajai",
    email: "ajaisalemopeyemi@gmail.com",
    matric: 229098,
    admin: 100100,
  },
  {
    firstName: "Odunayo",
    lastName: "Lawal",
    email: "lawalodunayo24@gmail.com",
    matric: 229131,
    admin: 100100,
  },

  {
    firstName: "David",
    lastName: "Adams",
    email: "adamsoluwatimilehin@gmail.com",
    matric: 206041,
    admin: 100100,
  },
  {
    firstName: "Moses",
    lastName: "Osuide",
    email: "mosesosuide@gmail.com",
    matric: 206058,
    admin: 100100,
  },
  {
    firstName: "Adedamola",
    lastName: "Adedoyin Ibrahim",
    email: "ibrahimadedoyeen@gmail.com",
    matric: 204923,
    admin: 100100,
  },
  {
    firstName: "Jesutofunmi",
    lastName: "Taiwo",
    email: "taiwoabosede02@gmail.com",
    matric: 204948,
    admin: 100100,
  },
  {
    firstName: "Praise",
    lastName: "Alabi",
    email: "alabipraise57@gmail.com",
    matric: 204928,
    admin: 100100,
  },
  {
    firstName: "Marvellous",
    lastName: "Olatoye",
    email: "marvellous.olatoye@gmail.com",
    matric: 206053,
    admin: 100100,
  },
  {
    firstName: "Daniel",
    lastName: "Ranti",
    email: "leinad.itnar@gmail.com",
    matric: 206060,
    admin: 100100,
  },
  {
    firstName: "Marvellous",
    lastName: "BADMUS",
    email: "badmusmarvy@gmail.com",
    matric: 206048,
    admin: 100100,
  },
  {
    firstName: "Mofetoluwa",
    lastName: "Ishola",
    email: "isholamofetoluwa@gmail.com",
    matric: 204937,
    admin: 100100,
  },
  {
    firstName: "Tobiloba",
    lastName: "Cole",
    email: "coleoluwatobiloba@gmail.com",
    matric: 204934,
    admin: 100100,
  },
  {
    firstName: "Mercy Oluwafisayomi",
    lastName: "Oyelalu",
    email: "oyelalumercy@gmail.com",
    matric: 208310,
    admin: 100100,
  },
  {
    firstName: "Oluwadara Titilayo",
    lastName: "Abolaji",
    email: "olubaby003@gmail.com",
    matric: 204921,
    admin: 100100,
  },
  {
    firstName: "Philip",
    lastName: "Arogundade",
    email: "philipheadlines@gmail.com",
    matric: 206047,
    admin: 100100,
  },
  {
    firstName: "Kehinde D",
    lastName: "Olusegun",
    email: "olusegunkehinde02@gmail.com",
    matric: 206056,
    admin: 100100,
  },
  {
    firstName: "Awal O.",
    lastName: "Oyedeji",
    email: "oyeyemiawal@gmail.com",
    matric: 206059,
    admin: 100100,
  },
  {
    firstName: "Daniel",
    lastName: "Ugwu",
    email: "danielugwu259@gmail.com",
    matric: 206061,
    admin: 100100,
  },
  {
    firstName: "Monsurat Adeyoola",
    lastName: "Sulayman",
    email: "monsuratadeyoola@gmail.com",
    matric: 213256,
    admin: 100100,
  },
  {
    firstName: "Oluwaseun",
    lastName: "Adekitan",
    email: "Adeseunm123@gmail.com",
    matric: 204924,
    admin: 100100,
  },
  {
    firstName: "Williams",
    lastName: "Owoeye",
    email: "dawillty007@gmail.com",
    matric: 204945,
    admin: 100100,
  },
  {
    firstName: "Mercy",
    lastName: "Adeosun",
    email: "adeosunmercy1@gmail.com",
    matric: 206043,
    admin: 100100,
  },
  {
    firstName: "Mayowa",
    lastName: "Olaomito",
    email: "marthonyarts@gmail.com",
    matric: 204942,
    admin: 100100,
  },
  {
    firstName: "Mayowa Margaret",
    lastName: "Awojide",
    email: "mayowaawojide@gmail.com",
    matric: 204932,
    admin: 100100,
  },
  {
    firstName: "Zainab Oreoluwa",
    lastName: "Kuku",
    email: "zainabkuku142@gmail.com",
    matric: 206724,
    admin: 100100,
  },
  {
    firstName: "Adedamola",
    lastName: "Adedoyin",
    email: "adedamolaadedoyin260@gmail.com",
    matric: 206042,
    admin: 100100,
  },
  {
    firstName: "Ndulue",
    lastName: "Francisca",
    email: "franciscandulue@gmail.com",
    matric: 213240,
    admin: 100100,
  },
  {
    firstName: "Simeon",
    lastName: "Bassey",
    email: "basseysimeon123@gmail.com",
    matric: 204933,
    admin: 100100,
  },
  {
    firstName: "OLATUNDE JOHN",
    lastName: "AJIBOYE",
    email: "olatundetycoon@gmail.com",
    matric: 206044,
    admin: 100100,
  },
  {
    firstName: "Favour",
    lastName: "ANIMASAHUN",
    email: "favourmobolade@gmail.com",
    matric: 204929,
    admin: 100100,
  },
  {
    firstName: "Nurudeen",
    lastName: "Olatunji",
    email: "olatunjinurudeen2017@gmail.com",
    matric: 206054,
    admin: 100100,
  },
  {
    firstName: "Hammed Babatunde",
    lastName: "Jimoh",
    email: "hammedj80@gmail.com",
    matric: 206050,
    admin: 100100,
  },
  {
    firstName: "Widad Titilayo",
    lastName: "Oladigbolu",
    email: "widadoladigbolu@gmail.com",
    matric: 204941,
    admin: 100100,
  },
  {
    firstName: "Gilbert",
    lastName: "Simeon",
    email: "simeongilbert112@gmail.com",
    matric: 204947,
    admin: 100100,
  },
  {
    firstName: "Ekene Augustine",
    lastName: "Nwagwu",
    email: "anwagwu051@stu.ui.edu.ng",
    matric: 206051,
    admin: 100100,
  },
  {
    firstName: "Benjamin Adesumbo",
    lastName: "Adediran",
    email: "Benadediran96@gmail.com",
    matric: 204922,
    admin: 100100,
  },
  {
    firstName: "Abdumujeeb Damola",
    lastName: "Opatola",
    email: "opatolaabdulmujeeb0@gmail.com",
    matric: 206057,
    admin: 100100,
  },
  {
    firstName: "Ojo Amusa",
    lastName: "Adebidemi",
    email: "Ojoamusa53@gmail.com",
    matric: 206052,
    admin: 100100,
  },
  {
    firstName: "Daniel",
    lastName: "Anyirionye",
    email: "daniel.anyirionye@gmail.com",
    matric: 206046,
    admin: 100100,
  },
  {
    firstName: "Luke Oyibome",
    lastName: "Egigba",
    email: "oyibomeegigba@gmail.com",
    matric: 204936,
    admin: 100100,
  },
  {
    firstName: "Seun Samuel",
    lastName: "Arowolo",
    email: "arowoloseun1@gmail.com",
    matric: 204930,
    admin: 100100,
  },
  {
    firstName: "Mercy",
    lastName: "Ojediran",
    email: "mercyojediran8@gmail.com",
    matric: 204940,
    admin: 100100,
  },
  {
    firstName: "Betty",
    lastName: "Olaosebikan",
    email: "betzgem@gmail.com",
    matric: 204943,
    admin: 100100,
  },
  {
    firstName: "Dorcas Damilola",
    lastName: "Olubunmi",
    email: "dolubunmi055@stu.ui.edu.ng",
    matric: 206055,
    admin: 100100,
  },
  {
    firstName: "Akinsola Temiloluwa",
    lastName: "Motunrayo",
    email: "akinsolatemiloluwa99@gmail.com",
    matric: 206049,
    admin: 100100,
  },
  {
    firstName: "Akinmolayan Tomide",
    lastName: "Ehijagbon",
    email: "tomillionxander@gmail.com",
    matric: 206045,
    admin: 100100,
  },
  {
    firstName: "OLAIYA EMMANUEL",
    lastName: "O",
    email: "Emexola89@gmail.com",
    matric: 213247,
    admin: 100100,
  },
  {
    firstName: "ADISA MORENIKE",
    lastName: "DEBORAH",
    email: "morenikeadisa@gmail.com",
    matric: 204925,
    admin: 100100,
  },
  {
    firstName: "Owolabi",
    lastName: "Esan",
    email: "owolabivengeance@gmail.com",
    matric: 213251,
    admin: 100100,
  },
  {
    firstName: "Oluwasegun Michael",
    lastName: "Osinowo",
    email: "shegzhyboltzmann05@gmail.com",
    matric: 220686,
    admin: 100100,
  },
  {
    firstName: "Oladotun Paul",
    lastName: "Olakunle",
    email: "olakunlepaul20@gmail.com",
    matric: 220679,
    admin: 100100,
  },
  {
    firstName: "Oluwatobiloba Joshua",
    lastName: "Ibitoye",
    email: "oluwatobiibitoye13@gmail.com",
    matric: 220670,
    admin: 100100,
  },
  {
    firstName: "Mabel Praises",
    lastName: "Aruwajoye",
    email: "princessiyinmipo@gmail.com",
    matric: 229176,
    admin: 100100,
  },
  {
    firstName: "Deborah Aayooluwa",
    lastName: "Animashaun",
    email: "danimashaun175@stu.ui.edu.ng",
    matric: 229175,
    admin: 100100,
  },
  {
    firstName: "Damilare Adewale",
    lastName: "Adekunle",
    email: "dadekunle655@stu.ui.edu.ng",
    matric: 220655,
    admin: 100100,
  },
  {
    firstName: "Marvellous Ebun",
    lastName: "Korede",
    email: "mkorede671@stu.ui.edu.ng",
    matric: 220671,
    admin: 100100,
  },
  {
    firstName: "Abdullahi Adebayo",
    lastName: "Kareem",
    email: "akareem187@stu.ui.edu.ng",
    matric: 229187,
    admin: 100100,
  },
  {
    firstName: "Ruqayyah Abiodun",
    lastName: "Bello",
    email: "ruqayyahabello@gmail.com",
    matric: 220665,
    admin: 100100,
  },
  {
    firstName: "Abuoma Elizabeth",
    lastName: "Ejikeme",
    email: "aejikeme666@stu.ui.edu.ng",
    matric: 220666,
    admin: 100100,
  },
  {
    firstName: "Richard Oluwasegun",
    lastName: "Oluagunloye",
    email: "roluagunloye683@stu.ui.edu.ng",
    matric: 220683,
    admin: 100100,
  },
  {
    firstName: "Michael Chinomso",
    lastName: "Meribe",
    email: "mmeribe673@stu.ui.edu.ng",
    matric: 220673,
    admin: 100100,
  },
  {
    firstName: "Valentina Racheal",
    lastName: "Atayero",
    email: "vatayero660@stu.ui.edu.ng",
    matric: 220660,
    admin: 100100,
  },
  {
    firstName: "Idayat Abiodun",
    lastName: "Lawal",
    email: "ilawal672@stu.ui.edu.ng",
    matric: 220672,
    admin: 100100,
  },

  {
    firstName: "Priscilla Oluwanifemi",
    lastName: "Ojediran",
    email: "pojediran677@stu.ui.edu.ng",
    matric: 220677,
    admin: 100100,
  },
  {
    firstName: "Maxwell Osasere",
    lastName: "Ogieriakhi",
    email: "mogieriakhi676@stu.ui.edu.ng",
    matric: 220676,
    admin: 100100,
  },
  {
    firstName: "Warith Ayobami",
    lastName: "Azeez",
    email: "wazeez662@stu.ui.edu.ng",
    matric: 220662,
    admin: 100100,
  },
  {
    firstName: "Sunday Enenche",
    lastName: "Oloche",
    email: "soloche681@stu.ui.edu.ng",
    matric: 220681,
    admin: 100100,
  },
  {
    firstName: "Gideon Olumide",
    lastName: "Alawode",
    email: "galawode659@stu.ui.edu.ng",
    matric: 220659,
    admin: 100100,
  },
  {
    firstName: "Abeeb Ayomide",
    lastName: "ALAO",
    email: "aalao658@stu.ui.edu.ng",
    matric: 220658,
    admin: 100100,
  },
  {
    firstName: "Tobi",
    lastName: "Olatunde",
    email: "olaphenomenal360@gmail.com",
    matric: 220680,
    admin: 100100,
  },
  {
    firstName: "Adeola Rebecca",
    lastName: "Famuyiwa",
    email: "afamuyiwa668@stu.ui.edu.ng",
    matric: 220668,
    admin: 100100,
  },
  {
    firstName: "Balogun Adewale",
    lastName: "Abdulmueed",
    email: "abalogun664@stu.ui.edu.ng",
    matric: 220664,
    admin: 100100,
  },
  {
    firstName: "Damilola Aderayo",
    lastName: "Bakare",
    email: "dbakare663@stu.ui.edu.ng",
    matric: 220663,
    admin: 100100,
  },
  {
    firstName: "Samuel Oluwatosin",
    lastName: "Olojo",
    email: "solojo682@stu.ui.edu.ng",
    matric: 220682,
    admin: 100100,
  },
  {
    firstName: "Isaac Akinyemi",
    lastName: "Morakinyo",
    email: "imorakinyo674@stu.ui.edu.ng",
    matric: 220674,
    admin: 100100,
  },
  {
    firstName: "Oyindamola Adesola",
    lastName: "Adegoke",
    email: "aadegoke654@stu.ui.edu.ng",
    matric: 220654,
    admin: 100100,
  },
  {
    firstName: "Grace Ibidun",
    lastName: "Adeleke",
    email: "gadeleke656@stu.ui.edu.ng",
    matric: 220656,
    admin: 100100,
  },
  {
    firstName: "Saheed Babatunde",
    lastName: "Adedokun",
    email: "radicalsa95@gmail.com",
    matric: 100100,
    admin: 100100,
  },
  {
    firstName: "Joseph Avwerosuo",
    lastName: "Odjirigho",
    email: "jodjirigho675@stu.ui.edu.ng",
    matric: 220675,
    admin: 100100,
  },

  {
    firstName: "Samuel Oluwapelumi",
    lastName: "Oladele",
    email: "soladele678@stu.ui.edu.ng",
    matric: 220678,
    admin: 100100,
  },
  {
    firstName: "Ajibola Solomon",
    lastName: "Oni",
    email: "aoni684@stu.ui.edu.ng",
    matric: 220684,
    admin: 100100,
  },
  {
    firstName: "Aliu Alade",
    lastName: "Adebayo",
    email: "aadebayo652@stu.ui.edu.ng",
    matric: 220652,
    admin: 100100,
  },
  {
    firstName: "Damilare Sewedo",
    lastName: "Enayon",
    email: "denayon667@stu.ui.edu.ng",
    matric: 220667,
    admin: 100100,
  },
  {
    firstName: "Oladiipo",
    lastName: "Kehinde",
    email: "koladiipo189@stu.ui.edu.ng",
    matric: 229189,
    admin: 100100,
  },
  {
    firstName: "John",
    lastName: "Abu",
    email: "aduraferanmii@gmail.com",
    matric: 213226,
    admin: 100100,
  },
  {
    firstName: "Emmanuel Oluwabamiji",
    lastName: "Adebayo",
    email: "bamiji2001@gmail.com",
    matric: 213227,
    admin: 100100,
  },
  {
    firstName: "Mujahid",
    lastName: "Adedapo",
    email: "madedapo228@stu.ui.edu.ng",
    matric: 213228,
    admin: 100100,
  },
  {
    firstName: "Eliezer",
    lastName: "Adeleke",
    email: "eliezeradeleke2@gmail.com",
    matric: 213230,
    admin: 100100,
  },
  {
    firstName: "Aishat",
    lastName: "Adeniyi",
    email: "adeniyiaeesha@gmail.com",
    matric: 213231,
    admin: 100100,
  },
  {
    firstName: "Olukayode John",
    lastName: "Adeyoose",
    email: "adeyooseolukayode@gmail.com",
    matric: 213232,
    admin: 100100,
  },
  {
    firstName: "Ridwan Ayomide",
    lastName: "Agboola",
    email: "agboolaridwan25@gmail.com",
    matric: 213233,
    admin: 100100,
  },
  {
    firstName: "Victor Semiloore",
    lastName: "Ajayi",
    email: "loorevictor1@gmail.com",
    matric: 213234,
    admin: 100100,
  },
  {
    firstName: "Sarah Barakat",
    lastName: "Akinyemi",
    email: "akinyemisarah78@gmail.com",
    matric: 213235,
    admin: 100100,
  },
  {
    firstName: "Esther Oluwapelumi",
    lastName: "Apara",
    email: "estherapara29@gmail.com",
    matric: 213236,
    admin: 100100,
  },
  {
    firstName: "Oyindamola Motunrayo",
    lastName: "Balogun",
    email: "balsoyindamola@gmail.com",
    matric: 213237,
    admin: 100100,
  },
  {
    firstName: "Marufat Olayinka",
    lastName: "Hassan",
    email: "hassanmarufat2018@gmail.com",
    matric: 213238,
    admin: 100100,
  },
  {
    firstName: "Adejoh Emmanuel",
    lastName: "John",
    email: "johnadejohemmanuel2@gmail.com",
    matric: 213239,
    admin: 100100,
  },
  {
    firstName: "Isaac",
    lastName: "Odion",
    email: "odionisaacosamudiamen@gmail.com",
    matric: 213241,
    admin: 100100,
  },
  {
    firstName: "Ayobami",
    lastName: "Ogunyemi",
    email: "segunpeterayo@gmail.com",
    matric: 213242,
    admin: 100100,
  },
  {
    firstName: "Feranmi Taiwo",
    lastName: "Ojo",
    email: "ojoferanmi932@gmail.com",
    matric: 213243,
    admin: 100100,
  },
  {
    firstName: "Peace Oluwaseun",
    lastName: "Okunade",
    email: "seunokunade7@gmail.com",
    matric: 213244,
    admin: 100100,
  },
  {
    firstName: "Sodiq",
    lastName: "Oladeji",
    email: "oladejisodiq704@gmail.com",
    matric: 213245,
    admin: 100100,
  },
  {
    firstName: "Damilola Abraham",
    lastName: "Olagunju",
    email: "olagunjudamilola015@gmail.com",
    matric: 213246,
    admin: 100100,
  },
  {
    firstName: "Oluwaseyi John",
    lastName: "Oludipe",
    email: "oludipeoluwaseyi@gmail.com",
    matric: 213248,
    admin: 100100,
  },
  {
    firstName: "Luli Olakitan",
    lastName: "Olusola",
    email: "olusolaluli33@gmail.com",
    matric: 213249,
    admin: 100100,
  },
  {
    firstName: "Oluwadare",
    lastName: "Owolabi",
    email: "oowolabi252@stu.ui.edu.ng",
    matric: 213252,
    admin: 100100,
  },
  {
    firstName: "Elizabeth Glory",
    lastName: "Oyedele",
    email: "oyedeleelizabether130@gmail.com",
    matric: 213253,
    admin: 100100,
  },
  {
    firstName: "Faith Temiloluwa",
    lastName: "Oyelade",
    email: "oyeladefaith434@gmail.com",
    matric: 213254,
    admin: 100100,
  },
  {
    firstName: "Emmanuel Marvelous",
    lastName: "Oyelaran",
    email: "oyelaranemma2000@gmail.com",
    matric: 213255,
    admin: 100100,
  },
  {
    firstName: "Philip Abayomi",
    lastName: "Vincent",
    email: "vincentphilip90@gmail.com",
    matric: 213257,
    admin: 100100,
  },
  {
    firstName: "Oluwatomiwa Emmanuel",
    lastName: "Oresanwo",
    email: "oresanwotomiwa@gmail.com",
    matric: 220685,
    admin: 100100,
  },
  {
    firstName: "Sarah Eshioresefe",
    lastName: "Joseph",
    email: "sarahjoseph207760@gmail.com",
    matric: 207760,
    admin: 100100,
  },
  {
    firstName: "Olawale",
    lastName: "Taiwo",
    email: "taiworichie16@gmail.com",
    matric: 213538,
    admin: 100100,
  },
  {
    firstName: "NZEMEKE UDOKA",
    lastName: "FAVOUR",
    matric: 220737,
    email: "unzemeke737@stu.ui.edu.ng",
    admin: 100100,
  },
  {
    firstName: "ADESINA OLUWATOSIN",
    lastName: "DANIEL",
    matric: 220697,
    email: "tosinbro54@gmail.com",
    admin: 100100,
  },
  {
    firstName: "EMMANUEL CHRISTIANNAH",
    lastName: "OLUWATOYOSI",
    matric: 220723,
    email: "Cemmanuel723@stu.ui.edu.ng",
    admin: 100100,
  },
  {
    firstName: "OYEWUMI SAMUEL",
    lastName: "OLUWATOBILOBA",
    matric: 220750,
    email: "Oyewumioluwatobi561@gmail.com",
    admin: 100100,
  },
  {
    firstName: "AYOLEKE",
    lastName: "OREOLUWA",
    matric: 220718,
    email: "ayolekeoreoluwa@gmail.com",
    admin: 100100,
  },
  {
    firstName: "OLADAPO",
    lastName: "SAMUEL",
    matric: 220741,
    email: "Oladaposamuel907@gmail.com",
    admin: 100100,
  },
  {
    firstName: "ADEDOKUN OLUWAFEMI",
    lastName: "IBIKUNLE",
    matric: 220692,
    email: "Adefemiadedokun2@gmail.com",
    admin: 100100,
  },
  {
    firstName: "IBITOYE SAMUEL",
    lastName: "OLUWASEGUN",
    matric: 220729,
    email: "Psalmsheg@gmail.com",
    admin: 100100,
  },
  {
    firstName: "ANI JOY",
    lastName: "NKECHINYERE",
    matric: 220711,
    email: "Jani711@stu.ui.edu.ng",
    admin: 100100,
  },
  {
    firstName: "KAYODE OLORUNTONILOBA",
    lastName: "ROSEMARY",
    matric: 223823,
    email: "okayode823@stu.ui.edu.ng",
    admin: 100100,
  },
  {
    firstName: "ODOR GLORY",
    lastName: "CHIDINMA",
    matric: 223824,
    email: "Godor824@stu.ui.edu.ng",
    admin: 100100,
  },
  {
    firstName: "JIMOH FARUK",
    lastName: "ADEMOLA",
    matric: 220732,
    email: "Jfaruk519@gmail.com",
    admin: 100100,
  },
  {
    firstName: "QOMORUDEEN AISHAT",
    lastName: "OLATUNDUN",
    matric: 220753,
    email: "Qomorudeenaishat2017@gmail.com",
    admin: 100100,
  },
  {
    firstName: "OLUOKUN",
    lastName: "OLADAYO",
    matric: 220747,
    email: "oluokunoladayo@gmail.com",
    admin: 100100,
  },
  {
    firstName: "OLUDARE FOLUSHO",
    lastName: "ABIMBOLA",
    matric: 214545,
    email: "Foludare545@stu.ui.edu.ng",
    admin: 100100,
  },
  {
    firstName: "AGBOOLA DANIEL",
    lastName: "DAMILARE",
    matric: 220700,
    email: "Dagboola700@stu.ui.edu.ng",
    admin: 100100,
  },
  {
    firstName: "UTHMAN UMIKULTHUM",
    lastName: "ABIOLA",
    matric: 223733,
    email: "Uuthman733@stu.ui.edu.ng",
    admin: 100100,
  },
  {
    firstName: "ALIMI ABDULSALAM",
    lastName: "AYODELE",
    matric: 220709,
    email: "Aalimi709@stu.ui.edu.ng",
    admin: 100100,
  },
  {
    firstName: "OMOLE",
    lastName: "PROSPER",
    matric: 220748,
    email: "Pomole748@stu.ui.edu.ng",
    admin: 100100,
  },
  {
    firstName: "OLADIMEJI",
    lastName: "JESUTOMILOLA",
    matric: 220743,
    email: "Joladimeji743@stu.ui.edu.ng",
    admin: 100100,
  },
  {
    firstName: "AYANWOLA",
    lastName: "TOFUNMI",
    matric: 220716,
    email: "Tayanwola716@stu.ui.edu.ng",
    admin: 100100,
  },
  {
    firstName: "AYENI OLUWANIFESIMI",
    lastName: "MERCY",
    matric: 220717,
    email: "Oayeni717@stu.ui.edu.ng",
    admin: 100100,
  },
  {
    firstName: "ITHENUMAH TIMOTHY",
    lastName: "OSHONE",
    matric: 220731,
    email: "Tithenumah731@stu.ui.edu.ng",
    admin: 100100,
  },
  {
    firstName: "OYENIRAN MONILOLA",
    lastName: "AYOMIDE",
    matric: 223655,
    email: "Moyeniran655@stu.ui.edu.ng",
    admin: 100100,
  },
  {
    firstName: "EMERAGOH DANIEL",
    lastName: "",
    matric: 220722,
    email: "Demeragoh722@stu.ui.edu.ng",
    admin: 100100,
  },
  {
    firstName: "ADENIJI WAHAB",
    lastName: "BOLUWATIFE",
    matric: 220695,
    email: "Wadeniji695@stu.ui.edu.ng",
    admin: 100100,
  },
  {
    firstName: "OMOTIMEHIN EMMANUEL",
    lastName: "OLUWAGBENGA",
    matric: 223988,
    email: "Eomotimehin988@stu.ui.edu.ng",
    admin: 100100,
  },
  {
    firstName: "OLADEJO YASIN",
    lastName: "ADEMOLA",
    matric: 220742,
    email: "Yoladejo742@stu.ui.edu.ng",
    admin: 100100,
  },
  {
    firstName: "KOLAPO BOLUWATIFE",
    lastName: "DEBORAH",
    matric: 220733,
    email: "Bkolapo733@stu.ui.edu.ng",
    admin: 100100,
  },
  {
    firstName: "AJALA STEPHEN",
    lastName: "OLUWATIMILEHIN",
    matric: 220701,
    email: "Sajala701@stu.ui.edu.ng",
    admin: 100100,
  },
  {
    firstName: "ADEMOKOYA KIKUNOLUWA",
    lastName: "BERAIAH",
    matric: 220694,
    email: "Kademokoya694@stu.ui.edu.ng",
    admin: 100100,
  },
  {
    firstName: "AREMU ENIOLA",
    lastName: "REBECCA",
    matric: 220713,
    email: "Earemu713@stu.ui.edu.ng",
    admin: 100100,
  },
  {
    firstName: "CHUKWUNYERE SUCCESS",
    lastName: "CHIOMA",
    matric: 220721,
    email: "Schukwunyere721@stu.ui.edu.ng",
    admin: 100100,
  },
  {
    firstName: "BASHIR UTHMAN",
    lastName: "OPEYEMI",
    matric: 220720,
    email: "Ubashir720@stu.ui.edu.ng",
    admin: 100100,
  },
  {
    firstName: "IKYOON COLLINS",
    lastName: "AONDOAVER",
    matric: "Cikyoon730@stu.ui.edu.ng",
    admin: 100100,
  },
  {
    firstName: "KILANKO",
    lastName: "FOLAHAN",
    matric: 229244,
    email: "Fkilanko244@stu.ui.edu.ng",
    admin: 100100,
  },
  {
    firstName: "ALAYEMI",
    lastName: "SAMUEL",
    matric: 220708,
    email: "Salayemi708@stu.ui.edu.ng",
    admin: 100100,
  },
  {
    firstName: "ALARAPE OLATUNDE",
    lastName: "MUEEZ",
    matric: 220707,
    email: "Oalarape707@stu.ui.edu.ng",
    admin: 100100,
  },
  {
    firstName: "OLOYEDE",
    lastName: "KOREDE",
    matric: 220746,
    email: "Koloyede746@stu.ui.edu.ng",
    admin: 100100,
  },
  {
    firstName: "LAWANI SAMSON",
    lastName: "TAYO",
    matric: 220735,
    email: "Slawani735@stu.ui.edu.ng",
    admin: 100100,
  },
  {
    firstName: "OKUNOLA RACHAEL",
    lastName: "MOROMOKE",
    matric: 220740,
    email: "Rokunola740@stu.ui.edu.ng",
    admin: 100100,
  },
  {
    firstName: "ABIODUN",
    lastName: "DORCAS",
    matric: 223903,
    email: "Dabiodun903@stu.ui.edu.ng",
    admin: 100100,
  },
  {
    firstName: "AWOYODE OLUWASANMI",
    lastName: "EMMANUEL",
    matric: 220715,
    email: "Oawoyode715@stu.ui.edu.ng",
    admin: 100100,
  },
  {
    firstName: "Cosmos",
    lastName: "Eze",
    email: "ceze724@stu.ui.edu.ng",
    matric: 220724,
    admin: 100100,
  },
  {
    firstName: "Prince",
    lastName: "Ogbonna",
    email: "pogbonna738@stu.ui.edu.ng",
    matric: 220738,
    admin: 100100,
  },
  {
    firstName: "Oluwamayowa",
    lastName: "Olasugba",
    email: "oolasugba745@stu.ui.edu.ng",
    matric: 220745,
    admin: 100100,
  },
  {
    firstName: "Oluwafemi",
    lastName: "Araoye",
    email: "oaraoye712@stu.ui.edu.ng",
    matric: 220712,
    admin: 100100,
  },
  {
    firstName: "Favour Taiwo",
    lastName: "Adebayo",
    email: "fadebayo690@stu.ui.edu.ng",
    matric: 220690,
    admin: 100100,
  },
  {
    firstName: "Olamide Maryam",
    lastName: "Adebisi",
    email: "oadebisi691@stu.ui.edu.ng",
    matric: 220691,
    admin: 100100,
  },
  {
    firstName: "Anuoluwapo Ayoade",
    lastName: "Owoade",
    email: "aowoade749@stu.ui.edu.ng",
    matric: 220749,
    admin: 100100,
  },
  {
    firstName: "Rofiat",
    lastName: "Agbajelola",
    email: "ragbajelola699@stu.ui.edu.ng",
    matric: 220699,
    admin: 100100,
  },
  {
    firstName: "Otitoluwa",
    lastName: "Fatoki",
    email: "ofatoki727@stu.ui.edu.ng",
    matric: 220727,
    admin: 100100,
  },
  {
    firstName: "Oluwafikayomi",
    lastName: "Bamigbopa",
    email: "obamigbopa719@stu.ui.edu.ng",
    matric: 220719,
    admin: 100100,
  },
  {
    firstName: "Faith",
    lastName: "Okedele",
    email: "fokedele739@stu.ui.edu.ng",
    matric: 220739,
    admin: 100100,
  },
  {
    firstName: "Izuchukwu",
    lastName: "Ezenwa",
    email: "iezenwa725@stu.ui.edu.ng",
    matric: 220725,
    admin: 100100,
  },
  {
    firstName: "Abass",
    lastName: "Anjolaoluwa Mercy",
    email: "anjolaoluwa321@gmail.com",
    matric: 213460,
    admin: 100100,
  },
  {
    firstName: "Abdulkareem",
    lastName: "Aishah Suruuroh",
    email: "eesha.kareem@gmail.com",
    matric: 213461,
    admin: 100100,
  },
  {
    firstName: "Abodunrin",
    lastName: "Grace Ebunoluwa",
    email: "abogracie@gmail.com",
    matric: 213464,
    admin: 100100,
  },
  {
    firstName: "Adedeji",
    lastName: "Oluwatobi",
    email: "Oluwatobiadedeji058@gmail.com",
    admin: 100100,
  },
  {
    firstName: "Adelana",
    lastName: "Mary Oluwaseun",
    email: "adelanamary9@gmail.com",
    matric: 213466,
    admin: 100100,
  },
  {
    firstName: "Adeleke",
    lastName: "Adeyemi James",
    email: "yemiadeleke80@gmail.com",
    admin: 100100,
  },
  {
    firstName: "Adeleke",
    lastName: "Miracle Ifeoluwa",
    email: "mimiifeoluwa@gmail.com",
    matric: 213469,
    admin: 100100,
  },
  {
    firstName: "Adeoye",
    lastName: "Emmanuel",
    email: "adeoyeheritage@gmail.com",
    matric: 213470,
    admin: 100100,
  },
  {
    firstName: "Adepoju",
    lastName: "Peter Oluwaseun",
    email: "adepojupeter100@gmail.com",
    matric: 213471,
    admin: 100100,
  },
  {
    firstName: "Adesogan",
    lastName: "oluwatofunmilayo",
    email: "olorunepebe2002@gmail.com",
    matric: 213472,
    admin: 100100,
  },
  {
    firstName: "Adetunji",
    lastName: "Josephine Ebunoluwa",
    email: "adetunjijosephine@gmail.com",
    matric: 213473,
    admin: 100100,
  },
  {
    firstName: "Adeyemi",
    lastName: "Samuel Adekunle",
    email: "adeyemisamuel67@gmail.com",
    matric: 213474,
    admin: 100100,
  },
  {
    firstName: "Adeyemo",
    lastName: "Emmanuel Olakojo",
    email: "emmanueladeyemo25@gmail.com",
    admin: 100100,
  },
  {
    firstName: "Afolabi",
    lastName: "Sunday Israel",
    email: "afford846@gmail.com",
    matric: 213476,
    admin: 100100,
  },
  {
    firstName: "Agbebi",
    lastName: "Timothy Oluwaseyi",
    email: "agbebitimothy2000@gmail.com",
    matric: 213477,
    admin: 100100,
  },
  {
    firstName: "Aiwanfoh",
    lastName: "Peace Ofure",
    email: "aiwanfohpeace@gmail.com",
    admin: 100100,
  },
  {
    firstName: "Ajumobi",
    lastName: "Toluwalase Esther",
    email: "ajumobitoluwa@gmail.com",
    matric: 213480,
    admin: 100100,
  },
  {
    firstName: "Akanbi",
    lastName: "Damilare Alabi",
    email: "akanbidamilare2017@gmail.com",
    matric: 213481,
    admin: 100100,
  },
  {
    firstName: "Akinbode",
    lastName: "Heritage Greatness",
    email: "akinbodeheritage@gmail.com",
    matric: 213482,
    admin: 100100,
  },
  {
    firstName: "Akinkuade",
    lastName: "Waheed Oluwaseun",
    email: "jattoleeakinkuade@gmail.com",
    matric: 213483,
    admin: 100100,
  },
  {
    firstName: "Akinyemi",
    lastName: "David Olalekan",
    email: "dakinyemi484@stu.ui.edu.ng",
    matric: 213484,
    admin: 100100,
  },
  {
    firstName: "Akinyode",
    lastName: "Toluwanimi Joanna",
    email: "takinyode485@stu.ui.edu.ng",
    matric: 213485,
    admin: 100100,
  },
  {
    firstName: "Alarape",
    lastName: "Karimah Oyindamola",
    email: "rimaadamolaa30@gmail.com",
    matric: 213487,
    admin: 100100,
  },
  {
    firstName: "Alatise",
    lastName: "Omolayo Fayobi",
    email: "fayobio17@gmail.com",
    matric: 206746,
    admin: 100100,
  },
  {
    firstName: "Aletor",
    lastName: "Jeremiah Isimeme",
    email: "aletorjeremiah247@gmail.com",
    admin: 100100,
  },
  {
    firstName: "Alexander",
    lastName: "Victor Chidera",
    email: "vikkyalexy15@gmail.com",
    matric: 213489,
    admin: 100100,
  },
  {
    firstName: "Amusan",
    lastName: "Abigail Ebunoluwa",
    email: "amusanabigail@outlook.com",
    matric: 213490,
    admin: 100100,
  },
  {
    firstName: "Asama",
    lastName: "Temitope Rachel",
    email: "tasama491@stu.ui.edu.ng",
    matric: 213491,
    admin: 100100,
  },
  {
    firstName: "Awolusi",
    lastName: "Emmanuel Oluwadamilare",
    email: "awolusi20@gmail.com",
    matric: 213492,
    admin: 100100,
  },
  {
    firstName: "Ayoola",
    lastName: "Emmanuel Babatunde",
    email: "emmanuelayoola243@gmail.com",
    admin: 100100,
  },
  {
    firstName: "Ayorinde",
    lastName: "Jesupelumi Alaafiaoluwa",
    email: "alaafia99@gmail.com",
    matric: 213493,
    admin: 100100,
  },
  {
    firstName: "Azeez",
    lastName: "Zainab Olatundun",
    email: "azeezzainab0101@gmail.com",
    matric: 213494,
    admin: 100100,
  },
  {
    firstName: "Bello",
    lastName: "Moshudat Morenike",
    email: "moshudatbello@gmail.com",
    matric: 213498,
    admin: 100100,
  },
  {
    firstName: "Daniel",
    lastName: "Shalom Praise",
    email: "shalompraise2002@gmail.com",
    matric: 213499,
    admin: 100100,
  },
  {
    firstName: "Diyaolu",
    lastName: "Deborah Ayomide",
    email: "dhebeedheya@gmail.com",
    matric: 213500,
    admin: 100100,
  },
  {
    firstName: "Blessing",
    lastName: "Chidimma",
    email: "blessingchidimma254@gmail.com",
    matric: undefined,
    admin: 100100,
  },
  {
    firstName: "Emmanuel",
    lastName: "Emeka Oluwapelumi",
    email: "Emeks976@gmail.com",
    matric: undefined,
    admin: 100100,
  },
  {
    firstName: "Ijadele",
    lastName: "Opeyemi Elizabeth",
    email: "opeyemiijadele@gmail.com",
    matric: 213507,
    admin: 100100,
  },
  {
    firstName: "Ishola",
    lastName: "Zainab Bukola",
    email: "zainabbukola3690@gmail.com",
    matric: 213508,
    admin: 100100,
  },
  {
    firstName: "Izuchi",
    lastName: "Chizitelu Mmesoma",
    email: "Chizitelummesoma@gmail.com",
    matric: 213509,
    admin: 100100,
  },
  {
    firstName: "Jola-Moses",
    lastName: "Dorcas Jesutofunmi",
    email: "jolamdorcas@gmail.com",
    matric: 213512,
    admin: 100100,
  },
  {
    firstName: "Jumah",
    lastName: "Neemot Adebisi",
    email: "jumah20009@gmail.com",
    matric: 213513,
    admin: 100100,
  },
  {
    firstName: "Maroof",
    lastName: "Abeeb Olumide",
    email: "abeebdon@gmail.com",
    matric: 213515,
    admin: 100100,
  },
  {
    firstName: "Moshood",
    lastName: "Ibrahim Oyedepo",
    email: "4452oyedepo@gmail.com",
    matric: 213516,
    admin: 100100,
  },
  {
    firstName: "Odeyemi",
    lastName: "Opeoluwa David",
    email: "opeoluwadavid691@gmail.com",
    matric: 213518,
    admin: 100100,
  },
  {
    firstName: "Ofomah",
    lastName: "Evander Ikechukwu",
    email: "lexusrex5@gmail.com",
    matric: undefined,
    admin: 100100,
  },
  {
    firstName: "Ogboriga",
    lastName: "Patrick Olanrewaju",
    email: "patrickolanrewaju007@gmail.com",
    matric: 213520,
    admin: 100100,
  },
  {
    firstName: "Ohia",
    lastName: "Mercy Egwumma",
    email: "ohiamercy5@gmail.com",
    matric: 213521,
    admin: 100100,
  },
  {
    firstName: "Ojo",
    lastName: "Oluwaseun Vincent",
    email: "vincentoluwaseun@gmail.com",
    matric: 213522,
    admin: 100100,
  },
  {
    firstName: "Okeke",
    lastName: "Mabel Chukwuemelie",
    email: "mabelokeke002@gmail.com",
    matric: 213523,
    admin: 100100,
  },
  {
    firstName: "Olabowale",
    lastName: "Babalola Israel",
    email: "Babalolabowale01@gmail.com",
    matric: 213524,
    admin: 100100,
  },
  {
    firstName: "Olaleye",
    lastName: "Igbagbo",
    email: "igbagboleye@gmail.com",
    matric: 213528,
    admin: 100100,
  },
  {
    firstName: "Olaniyan",
    lastName: "Shaddai Olamide",
    email: "shaddaiolamide25@gmail.com",
    matric: 213529,
    admin: 100100,
  },
  {
    firstName: "Omojola",
    lastName: "Ayomide",
    email: "omojolaa952@gmail.com",
    matric: undefined,
    admin: 100100,
  },
  {
    firstName: "Onayemi",
    lastName: "Omotoyosi",
    email: "toyosionayemi@gmail.com",
    matric: 213532,
    admin: 100100,
  },
  {
    firstName: "Opakunbi",
    lastName: "Motunrayo Semilore",
    email: "mopakunbi533@stu.ui.edu.ng",
    matric: 213533,
    admin: 100100,
  },
  {
    firstName: "Ope",
    lastName: "Aminat Temitope",
    email: "amintope4real@gmail.com",
    matric: 213534,
    admin: 100100,
  },
  {
    firstName: "Orimadegun",
    lastName: "Promise Adebanjo",
    email: "OrimadegunAdebanjo@gmail.com",
    matric: 213535,
    admin: 100100,
  },
  {
    firstName: "Sanni",
    lastName: "Hureeyah Adebola",
    email: "hsanni536@stu.ui.edu.ng",
    matric: 213536,
    admin: 100100,
  },
  {
    firstName: "Shodeke",
    lastName: "Fiyinfoluwa Favour",
    email: "fiyinfoluwashodeke9@gmail.com",
    matric: undefined,
    admin: 100100,
  },
  {
    firstName: "Moshood",
    lastName: "Uthman",
    email: "umoshood517@stu.ui.edu.ng",
    matric: 213517,
    admin: 100100,
  },
  {
    firstName: "OLANISEBE",
    lastName: "Adetunji Oladeji",
    email: "adetunjiolanisebe1101@gmail.com",
    matric: 178171,
    admin: 100100,
  },
  {
    firstName: "Abodunrin",
    lastName: "Paul",
    email: "paulabodunrin43@gmail.com",
    matric: 229164,
    admin: 100100,
  },
  {
    firstName: "Adebesin",
    lastName: "Clement Olanrewaju",
    email: "adeclement02@gmail.com",
    matric: 229165,
    admin: 100100,
  },
  {
    firstName: "Adediran",
    lastName: "Victor Ayomide",
    email: "victorthecopywriter@gmail.com",
    matric: 29166,
    admin: 100100,
  },
  {
    firstName: "Adesile",
    lastName: "Emmanuel Oluwadamilare",
    email: "emmanueloluwadamilare96@gmail.com",
    matric: 229167,
    admin: 100100,
  },
  {
    firstName: "Adeyemo",
    lastName: "Fortunatus Israel",
    email: "adeyemolekan433@gmail.com",
    matric: 229169,
    admin: 100100,
  },
  {
    firstName: "Akande",
    lastName: "Hammed Adeleke",
    email: "hammedakande2020@gmail.com",
    matric: 229170,
    admin: 100100,
  },
  {
    firstName: "Akinade",
    lastName: "Daniel",
    email: "dakinade171@stu.ui.edu.ng",
    matric: 229171,
    admin: 100100,
  },
  {
    firstName: "Akintade",
    lastName: "Temiloluwa Ayomide",
    email: "akintadetemi19@gmail.com",
    matric: 229172,
    admin: 100100,
  },
  {
    firstName: "Akintayo",
    lastName: "Adewale Temitope",
    email: "iamakintayo@gmail.com",
    matric: 229173,
    admin: 100100,
  },
  {
    firstName: "Alabi",
    lastName: "Enoch Korede",
    email: "alabiecoch2019@gmail.com",
    matric: 229174,
    admin: 100100,
  },
  {
    firstName: "Atanda Joshua",
    lastName: "oluwaseun",
    email: "jsholuwaseun01@gmail.com",
    matric: 229177,
    admin: 100100,
  },
  {
    firstName: "Ayeni",
    lastName: "Anna Modupe",
    email: "annaayeni@gmail.com",
    matric: 229178,
    admin: 100100,
  },
  {
    firstName: "Ayoola",
    lastName: "Joshua",
    email: "joshuaayoola673@gmail.com",
    matric: 229179,
    admin: 100100,
  },
  {
    firstName: "Folorunsho",
    lastName: "David",
    email: "Dfolurunsho180@stu.ui.edu.ng",
    matric: 229180,
    admin: 100100,
  },
  {
    firstName: "Ibrahim",
    lastName: "Latifat Morenike",
    email: "ilatifat183@gmail.com",
    matric: 229181,
    admin: 100100,
  },
  {
    firstName: "IDOWU",
    lastName: "Daniel Oluwatunmise",
    email: "didowu182@stu.ui.edu.ng",
    matric: 229182,
    admin: 100100,
  },
  {
    firstName: "Idowu",
    lastName: "Samuel Toluwani",
    email: "idsam2002@gmail.com",
    matric: 229183,
    admin: 100100,
  },
  {
    firstName: "Idowu Victoria",
    lastName: "Oluwafunke",
    email: "vidowu184@stu.ui.edu.ng",
    matric: 229184,
    admin: 100100,
  },
  {
    firstName: "Ilesanmi Christiana",
    lastName: "Oyindamola",
    email: "ilesanmichristiana29@gmail.com",
    matric: 229185,
    admin: 100100,
  },
  {
    firstName: "Ilori Christianah",
    lastName: "Oluwadamilola",
    email: "ilorichristianah45@gmail.com",
    matric: 229186,
    admin: 100100,
  },
  {
    firstName: "Oladimeji",
    lastName: "muheez",
    email: "muheez.eringize@gmail.com",
    matric: 229190,
    admin: 100100,
  },
  {
    firstName: "Olaifa Sekayo",
    lastName: "Femi",
    email: "sekayof@gmail.com",
    matric: 229191,
    admin: 100100,
  },
  {
    firstName: "Olanrewaju",
    lastName: "ruqoyyah Adeola",
    email: "olanrewajurule@gmail.com",
    matric: 229192,
    admin: 100100,
  },
  {
    firstName: "Osinkolu",
    lastName: "Timileyin",
    email: "osinkolutimileyin0@gmail.com",
    matric: 229193,
    admin: 100100,
  },
  {
    firstName: "Ososanya",
    lastName: "Toluwalopemi",
    email: "ososanyatoluwalopemi@gmail.com",
    matric: 229194,
    admin: 100100,
  },
  {
    firstName: "Sanni",
    lastName: "Oluwatobiloba Femi",
    email: "oluwatobilobafemi25@gmail.com",
    matric: 229195,
    admin: 100100,
  },
  {
    firstName: "Sodeeq Habeebah",
    lastName: "Gbogbolomo",
    email: "sodeeqomotoyosi9@gmail.com",
    matric: 229196,
    admin: 100100,
  },
  {
    firstName: "Sulaiman Semiu",
    lastName: "Ayinde",
    email: "abdsemiuabidemi2019@gmail.com",
    matric: 229197,
    admin: 100100,
  },
  {
    firstName: "Adewale Samuel",
    lastName: "Ayomide",
    email: "ayomide2983@gmail.com",
    matric: 232068,
    admin: 100100,
  },
  {
    firstName: "adelola",
    lastName: "ademola",
    email: "aadelola205@stu.ui.edu.ng",
    matric: 229205,
    admin: 100100,
  },
  {
    firstName: "olagoke",
    lastName: "joseph",
    email: "jolagoke256@stu.ui.edu.ng",
    matric: 229256,
    admin: 100100,
  },
  {
    firstName: "akinsanya",
    lastName: "victor",
    email: "vakinsanya215@stu.ui.edu.ng",
    matric: 229215,
    admin: 100100,
  },
  {
    firstName: "gregory",
    lastName: "samuel",
    email: "sgregory235@stu.ui.edu.ng",
    matric: 229235,
    admin: 100100,
  },
  {
    firstName: "rahji",
    lastName: "abdulazeez",
    email: "aarahji271@stu.ui.edu.ng",
    matric: 229271,
    admin: 100100,
  },
  {
    firstName: "odewale",
    lastName: "favour",
    email: "fodewale251@stu.ui.edu.ng",
    matric: 229251,
    admin: 100100,
  },
  {
    firstName: "abegunde",
    lastName: "kehinde",
    email: "kabegunde199@stu.ui.edu.ng",
    matric: 229199,
    admin: 100100,
  },
  {
    firstName: "oluniyi",
    lastName: "precious",
    email: "poluniyi-rich260@stu.ui.edu.ng",
    matric: 229260,
    admin: 100100,
  },
  {
    firstName: "adeyemi",
    lastName: "adeola",
    email: "oadeyemi209@stu.ui.edu.ng",
    matric: 229209,
    admin: 100100,
  },
  {
    firstName: "adisa",
    lastName: "emmanuella",
    email: "eadisa210@stu.ui.edu.ng",
    matric: 229210,
    admin: 100100,
  },
  {
    firstName: "abdulrahmon",
    lastName: "quareeb",
    email: "qabdulrahmon198@stu.ui.edu.ng",
    matric: 229198,
    admin: 100100,
  },
  {
    firstName: "ajayi",
    lastName: "oluwaseun",
    email: "oajayi211@stu.ui.edu.ng",
    matric: 229211,
    admin: 100100,
  },
  {
    firstName: "bioku",
    lastName: "joshua oluwapelumi",
    email: "jbioku225@stu.ui.edu.ng",
    matric: 229225,
    admin: 100100,
  },
  {
    firstName: "onaolapo",
    lastName: "abosede oluwatosin",
    email: "aonaolapo265@stu.ui.edu.ng",
    matric: 229265,
    admin: 100100,
  },
  {
    firstName: "idiemuagele",
    lastName: "portia",
    email: "pidiemuagele239@stu.ui.edu.ng",
    matric: 229239,
    admin: 100100,
  },
  {
    firstName: "hisa",
    lastName: "naheemot opeyemi",
    email: "nhisa236@stu.ui.edu.ng",
    matric: 229236,
    admin: 100100,
  },
  {
    firstName: "mpieri",
    lastName: "ezinne thelma",
    email: "empieri249@stu.ui.edu.ng",
    matric: 229249,
    admin: 100100,
  },
  {
    firstName: "okonkwo",
    lastName: "winifred anwulika",
    email: "wonkonkwo253@stu.ui.edu.ng",
    matric: 229253,
    admin: 100100,
  },
  {
    firstName: "olanoye",
    lastName: "olajide abidemi",
    email: "oolanoye258@stu.ui.edu.ng",
    matric: 229258,
    admin: 100100,
  },
  {
    firstName: "oyewunmi",
    lastName: "dolapo",
    email: "doyewunmi269@stu.ui.edu.ng",
    matric: 229269,
    admin: 100100,
  },
  {
    firstName: "john",
    lastName: "ayodeji",
    email: "ajohn242@stu.ui.edu.ng",
    matric: 229242,
    admin: 100100,
  },
  {
    firstName: "abioye",
    lastName: "opeyemi",
    email: "oabioye200@stu.ui.edu.ng",
    matric: 229200,
    admin: 100100,
  },
  {
    firstName: "adeniyi",
    lastName: "abimbola olubukola",
    email: "aadeniyi206@stu.ui.edu.ng",
    matric: 229206,
    admin: 100100,
  },
  {
    firstName: "dada",
    lastName: "kolade daniel",
    email: "kdada227@stu.ui.edu.ng",
    matric: 229227,
    admin: 100100,
  },
  {
    firstName: "ogbonna",
    lastName: "nnamdi isaac",
    email: "Ngbonna252@stu.ui.edu.ng",
    matric: 229252,
    admin: 100100,
  },
  {
    firstName: "adeyemi",
    lastName: "damilare olalekan",
    email: "dadeyemi208@stu.ui.edu.ng",
    matric: 229208,
    admin: 100100,
  },
  {
    firstName: "ajayi",
    lastName: "tolulope gideon",
    email: "tajayi212@stu.ui.edu.ng",
    matric: 229212,
    admin: 100100,
  },
  {
    firstName: "ezekiel",
    lastName: "stephen",
    email: "sezekiel231@stu.ui.edu.ng",
    matric: 229231,
    admin: 100100,
  },
  {
    firstName: "momoh",
    lastName: "bamise tunmise",
    email: "bmomomh248@stu.ui.edu.ng",
    matric: 229248,
    admin: 100100,
  },

  {
    firstName: "Philip",
    lastName: "Idowu",
    email: "pidowu240@stu.ui.edu.ng",
    matric: 229240,
    admin: 100100,
  },
  {
    firstName: "Oluwapelumi",
    lastName: "Ifeoluwaju Oluranti",
    email: "ooluranti261@stu.ui.edu.ng",
    matric: 229261,
    admin: 100100,
  },
  {
    firstName: "Collins",
    lastName: "Ozoude",
    email: "cozoude270@stu.ui.edu.ng",
    matric: 229270,
    admin: 100100,
  },
  {
    firstName: "Majeed",
    lastName: "Danjuma Ibrahim",
    email: "mibrahim237@stu.ui.edu.ng",
    matric: 229237,
    admin: 100100,
  },
  {
    firstName: "Qudus",
    lastName: "Ayomide Adejumo",
    email: "qadejumo202@stu.ui.edu.ng",
    matric: 229202,
    admin: 100100,
  },
  {
    firstName: "Ransome",
    lastName: "Solomon Nwitoka",
    email: "rnwitoka250@stu.ui.edu.ng",
    matric: 229250,
    admin: 100100,
  },
  {
    firstName: "Boluwatife",
    lastName: "Funmilade Oyekunle",
    email: "boyekunle267@stu.ui.edu.ng",
    matric: 229267,
    admin: 100100,
  },
  {
    firstName: "Alexander",
    lastName: "Nnmadi Udechukwu",
    email: "audechukwu273@stu.ui.edu.ng",
    matric: 229273,
    admin: 100100,
  },
  {
    firstName: "Hamdalat",
    lastName: "Jimoh",
    email: "hjimoh241@stu.ui.edu.ng",
    matric: 229241,
    admin: 100100,
  },
  {
    firstName: "Opeyemi",
    lastName: "Olamide Oladejo",
    email: "ooladejo255@stu.ui.edu.ng",
    matric: 229255,
    admin: 100100,
  },
  {
    firstName: "Kafilat",
    lastName: "Temitope Akinola",
    email: "kakinola213@stu.ui.edu.ng",
    matric: 229213,
    admin: 100100,
  },
  {
    firstName: "Temiloluwa",
    lastName: "Adekunjo",
    email: "tadekunjo203@stu.ui.edu.ng",
    matric: 229203,
    admin: 100100,
  },
  {
    firstName: "Oluwakunmi",
    lastName: "Adenowo",
    email: "oadenowo207@stu.ui.edu.ng",
    matric: 229207,
    admin: 100100,
  },
  {
    firstName: "Ayodeji",
    lastName: "Peter Kolawole",
    email: "akolawole246@stu.ui.edu.ng",
    matric: 229246,
    admin: 100100,
  },
  {
    firstName: "Emeka",
    lastName: "Victor Ossai",
    email: "eossai266@stu.ui.edu.ng",
    matric: 229266,
    admin: 100100,
  },
  {
    firstName: "Emmanuel",
    lastName: "Adeleke",
    email: "eadeleke204@stu.ui.edu.ng",
    matric: 229204,
    admin: 100100,
  },
  {
    firstName: "Amarachi",
    lastName: "Precious Duru",
    email: "aduru229@stu.ui.edu.ng",
    matric: 229229,
    admin: 100100,
  },
  {
    firstName: "Ibrahim",
    lastName: "Ayomide Ayoola",
    email: "iayoola223@stu.ui.edu.ng",
    matric: 229223,
    admin: 100100,
  },
  {
    firstName: "Chineye",
    lastName: "Helena Okpe",
    email: "cokpe254@stu.ui.edu.ng",
    matric: 229254,
    admin: 100100,
  },
  {
    firstName: "Peter",
    lastName: "Oluwasegun Atebisun",
    email: "petebisun222@stu.ui.edu.ng",
    matric: 229222,
    admin: 100100,
  },
  {
    firstName: "Ayodeji",
    lastName: "Akosile",
    email: "aakosile217@stu.ui.edu.ng",
    matric: 229217,
    admin: 100100,
  },
  {
    firstName: "Bolu",
    lastName: "Muyiwa Kolawole",
    email: "bkolawole247@stu.ui.edu.ng",
    matric: 229247,
    admin: 100100,
  },
  {
    firstName: "Oluwafemi",
    lastName: "Oyeleye",
    email: "ooyeleye268@stu.ui.edu.ng",
    matric: 229268,
    admin: 100100,
  },
  {
    firstName: "Peace",
    lastName: "Kingsley",
    email: "pkingsley245@stu.ui.edu.ng",
    matric: 229245,
    admin: 100100,
  },
  {
    firstName: "Blessed",
    lastName: "Cletus",
    email: "bcletus226@stu.ui.edu.ng",
    matric: 229226,
    admin: 100100,
  },
  {
    firstName: "Ernest",
    lastName: "Aloga",
    email: "ealoga220@stu.ui.edu.ng",
    matric: 229220,
    admin: 100100,
  },
  {
    firstName: "Mary",
    lastName: "Anieama",
    email: "manieama221@stu.ui.edu.ng",
    matric: 229221,
    admin: 100100,
  },
  {
    firstName: "Similoluwa",
    lastName: "Adebayo",
    email: "sadebayo201@stu.ui.edu.ng",
    matric: 229201,
    admin: 100100,
  },
  {
    firstName: "Iwaleso Ezekiel",
    lastName: "Akintunde",
    email: "iakintunde216@stu.ui.edu.ng",
    matric: 229216,
    admin: 100100,
  },
  {
    firstName: "Kehinde Saidat",
    lastName: "Alade",
    email: "kalade218@stu.ui.edu.ng",
    matric: 229218,
    admin: 100100,
  },

  {
    firstName: "Unyime Edoekong",
    lastName: "Udoekong",
    email: "uuedoekong114@stu.ui.edu.ng",
    matric: 232114,
    admin: 100100,
  },
  {
    firstName: "Ridwan Ayomide",
    lastName: "Ibrahim",
    email: "ribrahim238@stu.ui.edu.ng",
    matric: 229230,
    admin: 100100,
  },
  {
    firstName: "Gideon Oluwatimileyin",
    lastName: "Kayode",
    email: "gkayode243@stu.ui.edu.ng",
    matric: 229243,
    admin: 100100,
  },
  {
    firstName: "Peter Oluwatobi",
    lastName: "Tunwagun",
    email: "ptunwagun272@stu.ui.edu.ng",
    matric: 229272,
    admin: 100100,
  },
  {
    firstName: "Ayotomiwa Isaac",
    lastName: "Babalola",
    email: "ababalola224@stu.ui.edu.ng",
    matric: 229224,
    admin: 100100,
  },
  {
    firstName: "Anuoluwapo",
    lastName: "Dorcas",
    email: "dorcasade1990@gmail.com",
    matric: 198346,
    admin: 100100,
  },
  {
    firstName: "Deborah",
    lastName: "Odunayo",
    email: "adepojudebra@gmail.com",
    matric: 198352,
    admin: 100100,
  },
  {
    firstName: "Oluwafemi",
    lastName: "Emmanuel",
    email: "femianski@gmail.com",
    matric: 198356,
    admin: 100100,
  },
  {
    firstName: "Mosunmola",
    lastName: "Jelilat Akeem-Omosanya",
    email: "jellylah2504@gmail.com",
    matric: 198358,
    admin: 100100,
  },
  {
    firstName: "Dorcas",
    lastName: "Oluwaseun Akinfemisoye",
    email: "phemisoye@gmail.com",
    matric: 198360,
    admin: 100100,
  },
  {
    firstName: "Elijah",
    lastName: "Taiwo Alao",
    email: "alaotaiwo145@gmail.com",
    matric: 198364,
    admin: 100100,
  },
  {
    firstName: "Precious",
    lastName: "Oluwashoyin Arokoyo",
    email: "arokoyoshoyinfunmi@gmail.com",
    matric: 198365,
    admin: 100100,
  },
  {
    firstName: "Precious",
    lastName: "Damilola Ayeni",
    email: "ayenidamilola2000@gmail.com",
    matric: 198367,
    admin: 100100,
  },
  {
    firstName: "Nneka",
    lastName: "Gloria Igbor",
    email: "itsofficialgloria@gmail.com",
    matric: 198376,
    admin: 100100,
  },
  {
    firstName: "Oluwadamilare",
    lastName: "Temitayo Iyede",
    email: "iyedetemitayo08@gmail.com",
    matric: 198379,
    admin: 100100,
  },
  {
    firstName: "Mayowa",
    lastName: "Deborah Labade",
    email: "pearldebz75@gmail.com",
    matric: 198382,
    admin: 100100,
  },
  {
    firstName: "Mary Magdalene",
    lastName: "Ogochukwu Mgbaechidimma",
    email: "omgbechidimma938@stu.ui.edu.ng",
    matric: 204938,
    admin: 100100,
  },
  {
    firstName: "Odunayo",
    lastName: "Emmanuel Ogidan",
    email: "emmabest670@gmail.com",
    matric: 198384,
    admin: 100100,
  },
  {
    firstName: "Mary",
    lastName: "Oluwatimileyin Ogunfolaji",
    email: "oluwatimileyinogunfolaji@gmail.com",
    matric: 198386,
    admin: 100100,
  },
  {
    firstName: "Comfort",
    lastName: "Oluwafunmi Oguntoye",
    email: "funm20@yahoo.com",
    matric: 199517,
    admin: 100100,
  },
  {
    firstName: "Elizabeth",
    lastName: "Oluwadamilola Oke",
    email: "oludamsy54@gmail.com",
    matric: 198387,
    admin: 100100,
  },
  {
    firstName: "Chioma",
    lastName: "Faithfulness Okolie",
    email: "faithfulnessokolie@gmail.com",
    matric: 198389,
    admin: 100100,
  },
  {
    firstName: "Toafeek",
    lastName: "Yemi Oladeji",
    email: "yemzy198391@gmail.com",
    matric: 198391,
    admin: 100100,
  },
  {
    firstName: "Vanessa",
    lastName: "Wuraola Olanrewaju",
    email: "wuralanre99@gmail.com",
    matric: 198393,
    admin: 100100,
  },
  {
    firstName: "Esther",
    lastName: "Toluwanimi Olarerin",
    email: "olarerintolu@gmail.com",
    matric: 198394,
    admin: 100100,
  },
  {
    firstName: "Mubaraqat",
    lastName: "Yemi Onifade",
    email: "yemimubaraqat@gmail.com",
    matric: 198397,
    admin: 100100,
  },
  {
    firstName: "Elizabeth",
    lastName: "Oluwatobiloba Peters",
    email: "oluwatobilobapeters001@gmail.com",
    matric: 198399,
    admin: 100100,
  },
];
